server {
    listen 80;
    server_name luxurylaneassistance.gr www.luxurylaneassistance.gr;
    location /.well-known/acme-challenge/ { root /var/www/lla-demo; }
    location / { return 301 https://lla-demo.httpal.com$request_uri; }
}
